---
# Changes here will be overwritten by Copier
_commit: v2.1.4-18-g036146e
_src_path: gh:remerge/template
project_id: ansible-role-nomad
project_license: apache-2.0
project_name: Ansible Role for Nomad
project_owner: core
project_type: ansible-role
run_workflows_for_all_branches: false
use_python: true
