---
# Changes here will be overwritten by Copier
_commit: v0.7.7
_src_path: https://github.com/remerge/template.git
google_cloud_project: ansible-role-nomad-[random_id]
google_cloud_region: europe-west4
google_cloud_zone: europe-west4-a
project_id: ansible-role-nomad
project_name: Ansible Role for Nomad
project_owner: sre
use_ansible: false
use_google_cloud_compute: false
use_google_cloud_dns: false
use_google_cloud_public_dns: false
use_python: true
use_terraform: false
use_terraform_google: false
